version: '3.7
services:
  # App backend service
  app:
    image: spring-boot-docker-postgres:latest
    container_name: webflux
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testing
