version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: testing
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  app:
    build: .
    ports:
      - '8080:8080'
    environment: 
      spring.r2dbc.url=r2dbc:postgresql://localhost:5432/testing
      spring.r2dbc.username=root spring.r2dbc.password=root
    depends_on:
      - db
